Hf/linedb install to clay or pyro
uqbar-dao/linedb pull request #33
Opened 2023-05-02 01:26 UTC by hosted-fornet

2023-05-02 02:49 UTC, hosted-fornet commented
Still a WIP as of 05356a2. Compiles, but I want to get integrated with %ziggurat/%pyro to test before marking this ready.

2023-05-03 17:54 UTC, tadad requested changes
left some comments, the core logic looks fine

2023-05-03 17:54 UTC, tadad commented on lib/linedb.hoon
> +    |_  non=*
why did you these marks back?

2023-05-03 17:54 UTC, tadad commented on lib/linedb.hoon
> +  ==
I don't think we should do this automatically for people - I think we should just have them keep them in their repo and since we import all files this is fine

2023-05-03 17:54 UTC, tadad commented on lib/linedb.hoon
> +  """
unless you are using this somewhere else I don't use this helper anymore

2023-05-03 17:54 UTC, tadad commented on app/linedb.hoon
> +  =/  did-vase-build-succeed=(each ~ @t)
why not just a (unit @t)?

2023-05-03 17:54 UTC, tadad commented on app/linedb.hoon
> +    %+  welp  boilerplate-files:ldb
we can get rid of this if we just expect people to have all standard files in their folder. The only exception is `/mar/vase/hoon` which we special made for `uqbuild`

2023-05-03 19:44 UTC, hosted-fornet commented on app/linedb.hoon
> +  =/  did-vase-build-succeed=(each ~ @t)
Changed to unit in 0ebb0a7

2023-05-03 19:44 UTC, hosted-fornet commented on app/linedb.hoon
> +    %+  welp  boilerplate-files:ldb
Removed in ddf1415

2023-05-03 19:44 UTC, hosted-fornet commented on lib/linedb.hoon
> +    |_  non=*
Removed in ddf1415

2023-05-03 19:45 UTC, hosted-fornet commented on lib/linedb.hoon
> +  ==
Removed in ddf1415

2023-05-03 19:45 UTC, hosted-fornet commented on lib/linedb.hoon
> +  """
Removed in 6f0094e

2023-05-03 21:13 UTC, merged